### ISSUE TITLE
lscpu module relies on jq but isn't very clear what happened in case of failure

### ISSUE THREAD

**Issue by craigcomstock** [basvandervlies/cf_surfsara_lib#100]
I added lscpu in def.json for scl_inventory_modules and ran an update and agent run.

There were only info messages for lscpu:

```
    info: Executing 'no timeout' ... '/var/cfengine/modules/scl/lscpu '
    info: Failed to parse JSON '' for module protocol: No data
    info: Completed execution of '/var/cfengine/modules/scl/lscpu '
```

This was due to the fact I didn't have `jq` installed.

Is there a way to make the module return an error? I believe so:

https://docs.cfengine.com/docs/3.18/reference-language-concepts-modules.html

```
All lines of output that do not match the module protocol are treated as errors.
```

So maybe you could add something to the lscpu script to print out an error if jq is not installed/found?

https://github.com/basvandervlies/cf_surfsara_lib/blob/38ebc2dc5b5a214e6410647716e774e33c3ebfb1/modules/lscpu

**Comment by basvandervlies** [comment]
Thanks for the pointer I will fix it

**Comment by craigcomstock** [comment]
> Thanks for the pointer I will fix it

My pleasure. Great to take a look around this library!
