### ISSUE TITLE
Update cfbs module version to match yours

### ISSUE THREAD

**Issue by craigcomstock** [basvandervlies/cf_surfsara_lib#106]
Hello,

We have added the ability to include a "release" suffix to version in cfbs modules. This will allow you to change your version from the current `0.1.3` to your actual version `1.3.0` and then if you need to make cfbs module specific changes like meta data etc you can just add a `-1` or `-2` at the end.

The change would be here: https://github.com/cfengine/build-index/blob/master/cfbs.json#L728
You will need to use a different commit sha with this change, so maybe make an empty commit in your repo?

We made the same sort of change to our masterfiles so that the version in build.cfengine.com matches the version of masterfiles itself instead of the module: e.g. 3.18.1-1 instead of 0.1.0, 0.2.0, etc. See the version drop-down here: https://build.cfengine.com/modules/masterfiles/

Hope this makes things a bit nicer for you. Let us know if you need any help making the change.

**Comment by basvandervlies** [comment]
Thanks @craigcomstock for the suggestion. I will update the `scl` it is indeed nicer ;-)

**Comment by basvandervlies** [comment]
Submitted a pull request for version 1.4.0:
 * https://github.com/cfengine/build-index/pull/250

**Comment by craigcomstock** [comment]
Thanks for the update!
