### ISSUE TITLE
mention jq is a dependency

### ISSUE THREAD

**Issue by craigcomstock** [basvandervlies/cf_surfsara_lib#99]
mention in docs and maybe add a nice error message in policy to check for it?

I found this in lscpu module: https://github.com/basvandervlies/cf_surfsara_lib/blob/38ebc2dc5b5a214e6410647716e774e33c3ebfb1/modules/lscpu

**Comment by basvandervlies** [comment]
Can I close this and continue in #100?

**Comment by craigcomstock** [comment]
> Can I close this and continue in #100?

Oh definitely. They were kind of dupes.
